version: "3.9"

services:
  java_db:
    image: mongo
    container_name: java_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: backend

  java_app:
    container_name: java_app
    image: images-attachment-app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    env_file:
      - ./.env
    environment:
      MONGODB_HOST: java_db
    depends_on:
      - java_db

volumes:
  data: { }

networks:
  default:
    name: app_network